// Mocks generated by Mockito 5.4.6 from annotations
// in cart_app/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cart_app/api/menu_repository.dart' as _i4;
import 'package:cart_app/api/order_repository.dart' as _i6;
import 'package:cart_app/models/cart_item.dart' as _i7;
import 'package:cart_app/models/menu_response.dart' as _i2;
import 'package:cart_app/models/order_detail.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMenuResponse_0 extends _i1.SmartFake implements _i2.MenuResponse {
  _FakeMenuResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetail_1 extends _i1.SmartFake implements _i3.OrderDetail {
  _FakeOrderDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MenuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMenuRepository extends _i1.Mock implements _i4.MenuRepository {
  MockMenuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.MenuResponse> getMenu(String? tableId) =>
      (super.noSuchMethod(
            Invocation.method(#getMenu, [tableId]),
            returnValue: _i5.Future<_i2.MenuResponse>.value(
              _FakeMenuResponse_0(this, Invocation.method(#getMenu, [tableId])),
            ),
          )
          as _i5.Future<_i2.MenuResponse>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i6.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> submitOrder({
    required String? tableId,
    required List<_i7.CartItem>? items,
    required String? customerNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitOrder, [], {
              #tableId: tableId,
              #items: items,
              #customerNote: customerNote,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#submitOrder, [], {
                  #tableId: tableId,
                  #items: items,
                  #customerNote: customerNote,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.OrderDetail> getOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrder, [orderId]),
            returnValue: _i5.Future<_i3.OrderDetail>.value(
              _FakeOrderDetail_1(this, Invocation.method(#getOrder, [orderId])),
            ),
          )
          as _i5.Future<_i3.OrderDetail>);
}
